sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rajjejosefsson/react-test -f ./client/Dockerfile.dev ./client # remember to move the context as well
# - docker build myotherproject
script:
  - docker run -e CI=true rajjejosefsson/react-test npm run test -- --coverage
# - docker run myotherproject

after_success:
  # Build our images
  - docker build -t rajjejosefsson/multi-client ./client # context to client folder, and will implicit use default Dockerfile
  - docker build -t rajjejosefsson/multi-nginx ./nginx
  - docker build -t rajjejosefsson/multi-server ./server
  - docker build -t rajjejosefsson/multi-worker ./worker

  # Add password into STDIN of docker login.
  - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push rajjejosefsson/multi-client
  - docker push rajjejosefsson/multi-nginx
  - docker push rajjejosefsson/multi-server
  - docker push rajjejosefsson/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker2"
  env: "MultiDocker2-env"
  bucket: "elasticbeanstalk-us-east-1-152918186330" # zipped file into Amazon S3
  bucket_path: "docker-multi" # folder name in s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on: # when to run  deploy - merge with master
    branch: main
